### ISSUE TITLE
Do a design change (Neumorphism)

### ISSUE THREAD

**Issue by shimphillip** [shimphillip/gotta-search-em-all#9]
The UI currently gives a retro/soft feelings. It would be cool to implement something like https://neumorphism.io/#55b9f3 across the project.

**Comment by b3u** [comment]
I think the current design fits the pokemon theme

**Comment by shimphillip** [comment]
@b3u Appreciate that! 

While that's true, I am inclining to do a design overhaul and remove 'retro and hardness' feel and would like to give a more soft and peaceful 'feel' as an experiment. It would also be awesome if we have a design change button toggle to switch between themes.
